# Generated by Django 5.1.2 on 2025-07-15 08:06

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_image_postimage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='یک لیست از هشتگ\u200cها که با کاما از هم جدا شده\u200cاند.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='هشتگ\u200cها'),
        ),
    ]
