# Generated by Django 5.1.2 on 2025-07-17 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0001_initial'),
        ('posts', '0006_post_comments_count_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neighborhoods.neighborhood', verbose_name='محله مربوطه'),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'عمومی (برای همه)'), ('NEIGHBORHOOD', 'فقط هم\u200cمحله\u200cای\u200cها')], default='PUBLIC', max_length=20, verbose_name='قابلیت مشاهده'),
        ),
    ]
