# Generated by Django 5.1.2 on 2025-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_neighborhood_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='سنجاق شده (مهم)'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('POST', 'پست عادی'), ('NEWS', 'خبر'), ('EVENT', 'رویداد')], default='POST', max_length=20, verbose_name='نوع پست'),
        ),
    ]
