# Generated by Django 5.1.2 on 2025-08-12 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_event'),
        ('users', '0004_businessprofile_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.businessprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'امتیاز کسب\u200cوکار',
                'verbose_name_plural': 'امتیازهای کسب\u200cوکارها',
                'unique_together': {('user', 'business_profile')},
            },
        ),
    ]
