# Generated by Django 5.1.2 on 2025-08-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rating'),
        ('users', '0004_businessprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='users.businessprofile', verbose_name='کسب\u200cوکار مرتبط'),
        ),
    ]
