# Generated by Django 5.1.2 on 2025-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام محله')),
                ('city', models.CharField(default='پیش فرض', help_text='نام شهری که این محله در آن قرار دارد.', max_length=100, verbose_name='شهر')),
                ('center_latitude', models.FloatField(verbose_name='عرض جغرافیایی مرکز محله')),
                ('center_longitude', models.FloatField(verbose_name='طول جغرافیایی مرکز محله')),
                ('radius_km', models.FloatField(default=1.0, verbose_name='شعاع تقریبی محله (کیلومتر)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محله',
                'verbose_name_plural': 'محله\u200cها',
                'ordering': ['city', 'name'],
                'unique_together': {('name', 'city')},
            },
        ),
    ]
