# Generated by Django 5.1.2 on 2025-06-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0001_initial'),
        ('users', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles_in_neighborhood', to='neighborhoods.neighborhood', verbose_name='محله'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles_in_neighborhood', to='neighborhoods.neighborhood', verbose_name='محله'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
    ]
