# Generated by Django 5.1.2 on 2025-08-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businessprofile_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='میانگین امتیاز'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط عدد قیمت را برای فیلتر کردن وارد کنید.', max_digits=12, null=True, verbose_name='قیمت پایه (برای فیلتر)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='price_string',
            field=models.CharField(blank=True, help_text='مثال: ۱۵۰,۰۰۰ تومان شروع از، یا ۲۰۰,۰۰۰ تومان هر جلسه', max_length=100, null=True, verbose_name='رشته قیمت'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازات'),
        ),
    ]
