# Generated by Django 5.1.2 on 2025-09-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_businessprofile_average_rating_and_more'),
        ('users', '0005_seed_categories'),
    ]

    operations = [
    ]
