# Generated by Django 5.1.2 on 2025-09-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_category_slug_alter_tag_slug'),
        ('users', '0008_seed_business_profiles'),
    ]

    operations = [
    ]
